services:
  apt-cacher-ng:
    image: mrjncsk/apt-cacher-ng:latest
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - ./apt-cache:/var/cache/apt-cacher-ng
      - ./apt-config:/etc/apt-cacher-ng
    restart: unless-stopped
