name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '6 6 * * 6'  # Läuft jeden Samstag um 6:06 Uhr UTC
  workflow_dispatch:  # Manuelle Auslösung via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        chmod +x smart-build.sh
        ./smart-build.sh
