name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '6 6 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tag
      id: vars
      run: |
        TAG=$(date +'%Y%m%d%H%M')
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Image tag will be: $TAG"

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/apt-cacher-ng:${{ env.TAG }} .
        docker tag ghcr.io/${{ github.repository_owner }}/apt-cacher-ng:${{ env.TAG }} ghcr.io/${{ github.repository_owner }}/apt-cacher-ng:latest
        docker push ghcr.io/${{ github.repository_owner }}/apt-cacher-ng:${{ env.TAG }}
        docker push ghcr.io/${{ github.repository_owner }}/apt-cacher-ng:latest
