name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        chmod +x smart-build.sh
        ./smart-build.sh

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker tag apt-cacher-ng ghcr.io/mrjncsk/apt-cacher-ng:latest
        docker push ghcr.io/mrjncsk/apt-cacher-ng:latest

    - name: Deploy Docker container
      run: |
        docker-compose up -d
      if: github.ref == 'refs/heads/main'
